# Generated by Django 4.0.5 on 2022-12-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pulish',
            new_name='publish',
        ),
    ]
